sudo: required
language: node_js

node_js:
  - "5"

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install -g codeclimate-test-reporter codecov
  - npm install

script:
  - docker run -it --rm -v $PWD/node_modules:/app/node_modules -v $PWD/package.json:/app/package.json -v $PWD/.babelrc:/app/.babelrc -v $PWD/src:/app/src -v $PWD/test:/app/test -e NODE_ENV=test semtech/mu-javascript-template npm run lint
  - docker run -it --rm -v $PWD/node_modules:/app/node_modules -v $PWD/package.json:/app/package.json -v $PWD/.babelrc:/app/.babelrc -v $PWD/src:/app/src -v $PWD/test:/app/test -v $PWD/coverage:/app/coverage -e NODE_ENV=test semtech/mu-javascript-template npm run test:cov

after_script:
  - sed 's/\/app\///' coverage/lcov.info | codeclimate-test-reporter
  - codecov
